# Generated by Django 5.1.4 on 2025-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefoods',
            name='quantity',
            field=models.CharField(max_length=5, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='storagefoods',
            name='weight',
            field=models.CharField(choices=[('10.1', '10 KG'), ('15.1', '15 KG'), ('20.1', '20 KG'), ('25.1', '25 KG')], max_length=5, verbose_name='Peso da ração'),
        ),
    ]
