# Generated by Django 5.1.4 on 2025-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storagefoods_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefoods',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
