# Generated by Django 5.1.4 on 2025-01-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_storagefoods_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='seller',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do Vendedor'),
        ),
    ]
