# Generated by Django 5.1.4 on 2025-01-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_storagemoviments'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagefoods',
            name='alert_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Alerta'),
        ),
    ]
