# Generated by Django 5.1.4 on 2025-01-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_storagefoods_alert_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemoviments',
            name='moviment_type',
            field=models.CharField(max_length=15, verbose_name='Ação'),
        ),
    ]
