# Generated by Django 5.1.4 on 2025-01-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_storagemoviments_moviment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemoviments',
            name='moviment_type',
            field=models.CharField(max_length=6, verbose_name='Ação'),
        ),
    ]
