# Generated by Django 5.1.4 on 2025-02-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_storagemoviments_moviment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='contact_seller',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero do Vendedor'),
        ),
    ]
