# Generated by Django 5.1.4 on 2025-02-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_brands_contact_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefoods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='Imagem do Produto'),
        ),
    ]
