# Generated by Django 5.1.6 on 2025-03-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_storagefoods_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Data do Relatorio')),
                ('starter_quantity', models.IntegerField()),
                ('buy_quantity', models.IntegerField(default=0)),
                ('sell_quantity', models.IntegerField(default=0)),
                ('ending_quantity', models.IntegerField()),
                ('select_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storagefoods', verbose_name='Ração do Relatorio')),
            ],
        ),
    ]
