# Generated by Django 5.1.6 on 2025-03-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_storagemonthlyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemonthlyreport',
            name='ending_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
