# Generated by Django 5.1.6 on 2025-03-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_storagemonthlyreport_ending_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemonthlyreport',
            name='starter_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
