services:
  web-app:
    build: .
    restart: always
    container_name: petsfood_django
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/media
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - webnet
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
  
  database:
    image: postgres:16-alpine
    container_name: database
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles/
      - media_volume:/app/media
    depends_on:
      - web-app
    networks:
      - webnet
  
  cron:
    container_name: cron_command
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - web-app
      - database
    networks:
      - webnet
    restart: always
    entrypoint: ["/bin/sh", "-c", "cron && tail -f /dev/null"]

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  webnet:
    driver: bridge